    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: lms-be-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: lms-be
      template:
        metadata:
          labels:
            app: lms-be
        spec:
          containers:
          - name: lms-be-container
            image: pvdurgaprasadtrainer/lms-be:latest # Use the image built in step 2
            ports:
            - containerPort: 7070 # Or your application's port