apiVersion: v1
kind: Service
metadata:
  name: mariadb-headless
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 32760
      name: mariadb
  type: NodePort
  selector:
    app: mariadb