    apiVersion: v1
    kind: Service
    metadata:
      name: lms-be-service
    spec:
      selector:
        app: lms-be
      type: NodePort # Or ClusterIP, LoadBalancer (if supported by your Minikube setup)
      ports:
      - protocol: TCP
        port: 7070 # Service port
        targetPort: 7070 # Container port